// ============================================================================
// STUDY PLAN MODEL (backend/models/StudyPlan.js)
// ============================================================================
// Why this file exists:
// This file defines the exact structure for saving a "Study Plan" to the database.
// Previously, our planController generated the plan and sent it straight to the 
// user without saving it. By creating this Schema, we can now save a user's 
// daily study plan permanently so they can review past plans or stick to a 
// specific schedule over multiple days!

const mongoose = require('mongoose');

// ============================================================================
// STUDY PLAN SCHEMA (The Blueprint)
// ============================================================================
const studyPlanSchema = new mongoose.Schema(
  {
    // ========================================================================
    // FIELD 1: user (userId)
    // ========================================================================
    // Why it exists: Links this specific Study Plan to the student who requested it.
    // We use an ObjectId reference (Foreign Key) to tie it to the 'User' collection.
    // This ensures that when a student logs in, they only see THEIR generated plans, 
    // keeping their data completely private and secure.
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: [true, 'A Study Plan must belong to a user'],
    },

    // ========================================================================
    // FIELD 2: date
    // ========================================================================
    // Why it exists: A student might generate different plans for different days 
    // (e.g., studying 8 hours on Saturday, but only 2 hours on a Tuesday).
    // This Date field records WHICH day this specific plan is intended for.
    date: {
      type: Date,
      required: [true, 'Please provide a date for this study plan'],
      default: Date.now, // Defaults to today's date if not specified
    },

    // ========================================================================
    // FIELD 3: morningSession
    // ========================================================================
    // Why it exists: To store the subjects scheduled for the morning (peak focus).
    // We set the type to 'Array' (or a list) because a morning session might contain 
    // multiple subjects (e.g., 2 hours of Calculus, 1 hour of Physics).
    // We can store the exact slots generated by our planController here.
    morningSession: {
      type: Array,
      default: [], // Starts as an empty list if nothing is scheduled
    },

    // ========================================================================
    // FIELD 4: afternoonSession
    // ========================================================================
    // Why it exists: To store the subjects scheduled for the afternoon (medium focus).
    // Similar to the morning session, this array holds the specific subjects and 
    // hour allocations for the middle of the day.
    afternoonSession: {
      type: Array,
      default: [],
    },

    // ========================================================================
    // FIELD 5: eveningSession
    // ========================================================================
    // Why it exists: To store the subjects scheduled for the evening (light review).
    // This array holds the lowest-priority or easiest subjects.
    eveningSession: {
      type: Array,
      default: [],
    },

    // ========================================================================
    // FIELD 6: totalHours
    // ========================================================================
    // Why it exists: A quick reference for how many total hours the student committed 
    // to studying on this specific date. 
    // type: Number ensures it is saved as a mathematical number (e.g., 5.5).
    totalHours: {
      type: Number,
      required: [true, 'Please provide the total daily study hours'],
      min: [0.5, 'Total hours must be at least 0.5'],
      max: [24, 'Total hours cannot exceed 24'],
    },
  },
  {
    // ========================================================================
    // OPTION: timestamps (createdAt & updatedAt)
    // ========================================================================
    // EXPLAINING TIMESTAMPS:
    // By setting timestamps to true, Mongoose automatically injects two extra fields:
    // 1. createdAt: The exact timestamp when this plan was first saved to the database.
    // 2. updatedAt: The exact timestamp if the user ever edits the plan later.
    // This is incredibly useful for analytics and auditing without us having to write 
    // extra code to manage the dates!
    timestamps: true,
  }
);

// ============================================================================
// EXPORTING THE MODEL
// ============================================================================
// We compile the 'studyPlanSchema' blueprint into a fully functional Model called 'StudyPlan'.
// Mongoose will automatically create a collection called 'studyplans' in our MongoDB database.
const StudyPlan = mongoose.model('StudyPlan', studyPlanSchema);

module.exports = StudyPlan;
